<?php
 // module/Album/view/album/album/add.phtml:

 $title = 'Add new album';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('album', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
/*
 * // before we made change in "AlbumForm.php" . 
 *  echo $this->formRow($form->get('title'));
 *  echo $this->formRow($form->get('artist'));
 *  echo $this->formSubmit($form->get('submit'));
 * echo $this->form()->closeTag();
 */
 
 ?>
 <table>
     <tr>
         <td> <b>Title </b> </td>
         <td><?php echo $this->formRow($form->get('title')); ?></td>
     <tr>
         <td> <b>Artist</b> </td>
         <td> <?php echo $this->formRow($form->get('artist')); ?> </td>
     </tr>
     <tr>
         <td> <?php echo $this->formSubmit($form->get('submit')); ?> </td>
     </tr>
 </table>
 <?php 
 //echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 