<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Edit album';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'album',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 /*
  * // before we made change in "AlbumForm.php" 
  * echo $this->formRow($form->get('title'));
  * echo '<br>';
  * echo $this->formRow($form->get('artist'));
  *  echo '<br>';
  *  echo $this->formSubmit($form->get('submit'));
  * echo $this->form()->closeTag();
  */
 ?>
 <table>
     <tr>
         <td> <b> Title</b></td>
         <td> <?php echo $this->formRow($form->get('title')); ?></td>
     </tr>
     <tr>
         <td> <b> Artist</b></td>
         <td> <?php echo $this->formRow($form->get('artist')); ?></td>
     </tr>
     <tr>
         <td> <?php echo $this->formSubmit($form->get('submit')); ?> </td>
     </tr>
 </table>
 <?php
 echo $this->form()->closeTag();

