<?php

 $title = 'Add new album';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
  //var_dump($this->form2);
 $form2->setAttribute('action', $this->url('add', array('action' => 'add')));
 $form2->prepare();

 echo $this->form()->openTag($form2);
 echo $this->formHidden($form2->get('id'));
 echo $this->formRow($form2->get('title'));
 echo $this->formRow($form2->get('artist'));
 echo $this->formSubmit($form2->get('submit'));
 echo $this->form()->closeTag();