<?php

$title = 'Edit album';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form2 = $this->form2;
 //var_dump($this->id);//corect
 $form2->setAttribute('action', $this->url('edit',array('id'=> $this->id)
 ));
 $form2->prepare();

 echo $this->form()->openTag($form2);
 echo $this->formHidden($form2->get('id'));
 echo $this->formRow($form2->get('title'));
 echo $this->formRow($form2->get('artist'));
 echo $this->formSubmit($form2->get('submit'));
 echo $this->form()->closeTag();
