
<div ng-app="myApp" >
    <form id="lgForm" action="" method="post">
        <table>
            <tr>
                <td>
                    <label>User Name :</label>
                </td>
                <td>
                    <input  type="text" name="username" maxlength="30" required >
                </td>
            </tr>
            <tr>
                <td>
                    <label> Password :</label>
                </td>
                <td>
                    <input type="password" name="password" maxlength="30" required >
                </td>
            </tr>
            <tr>
                <td>
                    <input type="submit" name="submit" value="Log In">
                </td>
            </tr>
        </table>
        
    </form>
    
</div>
<?php 
   if ($this->messages){
    echo '<ul>';
    foreach($this->messages as $message)
    {
        echo '<li>'.$message.'</li>';
    }
    echo '</ul>';
}
?>
<script>
    var url = window.location.href ;
    
    $(document).ready(function(){
        $("#lgForm").attr('action', url + '/authenticate') ;
        
    });
       
</script>