
<h2 style="color:#006699"> Add New Students </h2>

<div ng-app="myApp" ng-controller="myCtrlAdd" >
    <form id="addForm" action="" method="post">
        <input type="hidden" name="id" >
        
        <table>
            <tr>
                <td>
                    <label> Name:</label>
                </td>
                <td>
                    <input type="text" name="name" maxlength="30" required >
                </td>
            </tr>
            <tr>
                <td>
                    <label> Department: </label>
                </td>
                <td>
                    <input type="text" name="department" maxlength="30" required > 
                </td>
            </tr>
            <tr>
                <td>
                    <input type="submit" name="Add" value="Add"> 
                </td>
            </tr>
        </table>
        
    </form>
    
</div>

<script>
    var url = window.location.href ;
    
    $(document).ready(function(){
        $("#addForm").attr('action', url);
        
    });
    
</script>
