<?php

$title = 'Add new Student';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php

 $form2->setAttribute('action', $this->url('success2', array('action' => 'add')));
 $form2->prepare();

 echo $this->form()->openTag($form2);
 echo $this->formHidden($form2->get('id'));

 ?>
 <table>
     <tr>
         <td> Name :</td>
         <td> <?php echo $this->formRow($form2->get('name')); ?></td>
     </tr>
     <tr>
         <td>Department :</td>
         <td> <?php  echo $this->formRow($form2->get('department')); ?></td>
     </tr>
     <tr>
         <td> <?php echo $this->formSubmit($form2->get('submit')); ?></td>
     </tr>
 </table>
 <?php 
 echo $this->form()->closeTag();
 