<?php

    $title = 'Edit Student';
    $this->headTitle($title);
?>
 <h1> <?php echo $this->escapeHtml($title); ?> </h1>

 <?php
    $form2 = $this->form2;
    //var_dump($this->id);//corect
     $form2->setAttribute('action', $this->url('success2',array('action'=>'edit','id'=> $this->id)
    ));
    $form2->prepare();

    echo $this->form()->openTag($form2);  // render or provide form open tag i.e. <form>
    echo $this->formHidden($form2->get('id'));

 ?>
 <table>
    <tr>
        <td> <b> Name: </b></td>
        <td> <?php echo $this->formRow($form2->get('name')); ?> </td>
    </tr>
    <tr>
        <td> <b> Department : </b> </td>
        <td> <?php echo $this->formRow($form2->get('department'));  ?> </td>
    </tr>
    <tr>
        <td> <?php  echo $this->formSubmit($form2->get('submit'));  ?> </td>
    </tr>
 </table>
 
 <?php echo $this->form()->closeTag(); ?>